recipe: default.v1
language: es
pipeline:
- name: CompactLLMCommandGenerator
  llm:
    model_group: rasa_command_generation_model
  flow_retrieval:
    active: false


policies:
- name: FlowPolicy
#  - name: EnterpriseSearchPolicy
  vector_store:
        type: faiss
        path: ./faiss_index.index
assistant_id: 20250820-195204-cheesy-estuary
