from datasets import Dataset

data = {
    "pregunta": [
        "¿Qué es la violencia intrafamiliar?",
        "¿Cuál es la definición legal de la violencia intrafamiliar en Colombia?",
        "¿Qué tipos de violencia pueden darse dentro del núcleo familiar?",
        "¿Se considera violencia intrafamiliar cuando no hay agresión física?",
        "¿Cómo se diferencia la violencia intrafamiliar de la violencia de género?",
        "¿Por qué es importante reconocer la violencia psicológica o emocional?",
        "¿Cuáles son las causas comunes de la violencia intrafamiliar?",
        "¿Qué factores sociales aumentan la probabilidad de violencia en el hogar?",
        "¿Cómo influyen los roles de género y los estereotipos culturales?",
        "¿Qué papel juega la dependencia económica en situaciones de violencia?",
        "¿Qué señales podrían indicar que alguien sufre violencia en el hogar?",
        "¿Cómo detectar la violencia emocional o psicológica?",
        "¿Qué indicios físicos son frecuentes en las víctimas?",
        "¿Cómo afecta la violencia intrafamiliar a los niños que la presencian?",
        "¿Qué cambios en el comportamiento podrían sugerir abuso invisible?",
        "¿Qué puedo hacer para protegerme si temo ser víctima?",
        "¿Cómo dialogar en el hogar para prevenir conflictos?",
        "¿Qué hábitos o ejercicios familiares ayudan a reforzar la convivencia pacífica?",
        "¿Cuándo debe una persona decidir buscar ayuda externa?",
        "¿Qué es la violencia física dentro del hogar?",
        "¿Cómo se manifiesta la violencia física en la familia?",
        "¿Cuáles son ejemplos de violencia física?",
        "¿Qué consecuencias tiene la violencia física en las víctimas?",
        "¿Cómo denunciar un caso de violencia física en el hogar?",
        "¿Qué hacer si un menor está sufriendo agresiones físicas?",
        "¿Qué es la violencia psicológica?",
        "¿Cuáles son los signos más comunes de violencia emocional?",
        "¿Por qué la violencia psicológica es tan dañina como la física?",
        "¿Cómo identificar si estoy sufriendo manipulación o control emocional?",
        "¿Qué puedo hacer si mi pareja me humilla o me controla?",
        "¿Cómo se puede sanar emocionalmente después de vivir violencia psicológica?",
        "¿Qué se considera violencia sexual dentro del hogar?",
        "¿Puede existir violencia sexual entre parejas casadas o convivientes?",
        "¿Qué hacer si una persona sufre abuso sexual en su casa?",
        "¿Cuáles son las señales de que un niño está siendo víctima de abuso sexual?",
        "¿Qué entidades brindan acompañamiento a víctimas de violencia sexual?",
        "¿Qué dice la Ley 1257 de 2008 sobre la violencia sexual?",
        "¿Qué es la violencia económica?",
        "¿Cuáles son ejemplos de violencia económica dentro del hogar?",
        "¿Qué diferencia hay entre violencia económica y patrimonial?",
        "¿Cómo puedo demostrar que estoy siendo víctima de control económico?",
        "¿Qué hacer si mi pareja no me deja trabajar o me quita mi salario?",
        "¿Qué protección da la ley contra la violencia patrimonial?",
        "¿Qué se entiende por violencia verbal?",
        "¿Qué frases o conductas pueden considerarse violencia verbal?",
        "¿Por qué los insultos constantes son una forma de violencia?",
        "¿Qué efectos tiene la violencia verbal a largo plazo?",
        "¿Cómo detener dinámicas familiares basadas en insultos o gritos?",
        "¿Dónde buscar ayuda psicológica si sufro maltrato verbal?",
        "¿Qué es la violencia simbólica dentro del entorno familiar?",
        "¿Cómo se expresa la violencia simbólica en la vida diaria?",
        "¿Qué es la violencia digital en el contexto intrafamiliar?",
        "¿Qué ejemplos hay de violencia digital?",
        "¿Cómo puedo proteger mi privacidad digital frente a un agresor?",
        "¿Qué leyes existen en Colombia para sancionar la violencia digital?",
        "¿Qué formas de violencia suelen sufrir con mayor frecuencia las mujeres en Colombia?",
        "¿Cómo puede una mujer identificar que está en una relación violenta?",
        "¿A dónde puede acudir una mujer víctima de violencia intrafamiliar?",
        "¿Los hombres también pueden ser víctimas de violencia intrafamiliar?",
        "¿Por qué los hombres tienden a no denunciar la violencia?",
        "¿Qué debe hacer un hombre víctima de violencia intrafamiliar?",
        "¿Qué es la violencia infantil?",
        "¿Cuáles son los signos más comunes de violencia infantil?",
        "¿A dónde se denuncia un caso de violencia contra un menor?",
        "¿Qué tipos de violencia afectan con más frecuencia a las personas mayores?",
        "¿Cómo se puede proteger a un adulto mayor víctima de maltrato?",
        "¿Qué es la violencia basada en identidad de género u orientación sexual?",
        "¿Qué ejemplos existen de violencia hacia personas trans o no binarias?",
        "¿Dónde pueden denunciar las personas LGBTIQ+ casos de violencia o discriminación?"
    ],
    "respuesta": [
        "La violencia intrafamiliar es cualquier acción u omisión que cause daño físico, psicológico, sexual, económico o patrimonial dentro del hogar.",
        "La Ley 294 de 1996 define la violencia intrafamiliar como todo acto de poder u omisión que cause daño a un integrante del grupo familiar.",
        "Incluye violencia física, psicológica, sexual, económica, patrimonial y verbal.",
        "Sí, las agresiones emocionales también son violencia intrafamiliar según la ley.",
        "La violencia intrafamiliar abarca todo el núcleo familiar, mientras que la de género se enfoca en agresiones por motivos de género.",
        "Porque la violencia emocional destruye la autoestima y puede derivar en otras formas de maltrato.",
        "Causas: machismo, dependencia económica, estrés, alcoholismo, celos y falta de comunicación.",
        "Factores sociales como pobreza, exclusión o falta de educación aumentan el riesgo de violencia.",
        "Los estereotipos de género perpetúan relaciones de poder desiguales y justifican el maltrato.",
        "La dependencia económica impide que muchas víctimas puedan salir del ciclo de violencia.",
        "Señales: miedo, aislamiento, ansiedad, excusas por lesiones o comportamiento evasivo.",
        "Si hay humillaciones, gritos o control constante, puede existir violencia emocional.",
        "Lesiones sin explicación clara, marcas repetidas o fracturas son indicios comunes.",
        "Los niños expuestos a violencia pueden reproducirla o sufrir traumas duraderos.",
        "Cambios bruscos de humor, retraimiento o bajo rendimiento son señales de alerta.",
        "Busca ayuda, contacta a una Comisaría de Familia o la Línea 155, y evita el aislamiento.",
        "Escuchar sin interrumpir, resolver conflictos sin gritar y practicar el respeto mutuo.",
        "Realizar ejercicios familiares de comunicación y resolución pacífica de conflictos.",
        "Debe hacerlo cuando el miedo o la agresión afectan su bienestar o seguridad.",
        "Es el uso de la fuerza física para causar daño, como golpes o empujones.",
        "Se manifiesta mediante agresiones físicas, castigos o lesiones visibles.",
        "Ejemplos: bofetadas, jalones, golpes con objetos o empujones.",
        "Provoca dolor, lesiones, traumas y miedo permanente.",
        "Debe denunciarse en una Comisaría de Familia o Fiscalía.",
        "Reportar inmediatamente al ICBF o Policía si hay menores afectados.",
        "Actos que dañan emocionalmente, como humillaciones o amenazas.",
        "Inseguridad, miedo, ansiedad, aislamiento y pérdida de autoestima.",
        "Porque genera dependencia y daño emocional profundo.",
        "Si te hacen sentir miedo o culpa constantemente, estás siendo manipulado.",
        "Habla con alguien de confianza o contacta la Línea 155.",
        "Buscar terapia o acompañamiento psicológico ayuda a sanar.",
        "Todo acto sexual sin consentimiento, incluso dentro del matrimonio.",
        "Sí, el matrimonio no elimina el derecho al consentimiento sexual.",
        "Buscar atención médica inmediata y denunciar ante la Fiscalía.",
        "Miedo, retraimiento o rechazo a ciertas personas pueden ser señales.",
        "La Fiscalía, Medicina Legal e ICBF brindan apoyo gratuito.",
        "La Ley 1257 protege a las víctimas y sanciona la violencia sexual.",
        "Control o negación del acceso a recursos económicos.",
        "Ejemplo: impedir trabajar, quitar el dinero o manipular bienes.",
        "La económica controla recursos; la patrimonial destruye bienes.",
        "Guardar pruebas como transferencias o mensajes puede ayudar.",
        "Puede denunciar en la Comisaría o Defensoría del Pueblo.",
        "La ley protege el acceso al patrimonio y sanciona el control económico.",
        "Uso de palabras que humillan o degradan.",
        "Frases ofensivas o gritos repetidos constituyen violencia verbal.",
        "Porque destruyen la autoestima y fomentan el miedo.",
        "Causa traumas emocionales y ansiedad crónica.",
        "Fomentar el respeto, acudir a terapia familiar si es necesario.",
        "Línea 106 o centros de salud mental ofrecen ayuda gratuita.",
        "Mensajes o gestos que refuerzan desigualdad o humillación.",
        "Ejemplo: chistes sexistas o imposición de roles de género.",
        "Uso de tecnología para acosar, controlar o difundir información íntima.",
        "Ejemplo: revisar el celular o difundir fotos sin permiso.",
        "Cambiar contraseñas y denunciar ante la Policía Cibernética.",
        "Ley 1273 y 1581 sancionan delitos informáticos y protegen la intimidad.",
        "Las mujeres sufren más violencia física, sexual y económica.",
        "Cuando siente miedo, control o humillación constante en su relación.",
        "Línea 155, Comisarías de Familia o Casas de Igualdad de Oportunidades.",
        "Sí, los hombres también pueden ser víctimas.",
        "Por miedo al estigma o por roles sociales que impiden reconocerlo.",
        "Debe denunciar en Comisaría, Fiscalía o Línea 123.",
        "Todo acto de maltrato, abuso o negligencia hacia un menor.",
        "Miedo, retraimiento, lesiones o bajo rendimiento escolar.",
        "Denunciar ante el ICBF, Policía de Infancia o Comisaría de Familia.",
        "Abuso económico, abandono o violencia psicológica.",
        "Acudir a Comisarías o Fiscalía para protección inmediata.",
        "Violencia motivada por identidad o expresión de género.",
        "Negar identidad, burlarse o excluir a personas trans es violencia.",
        "Denunciar en Fiscalía, Personería o Comisarías de Familia."
    ]
}

dataset = Dataset.from_dict(data)
dataset.push_to_hub("Yeso888/mini-dataset-prueba")